### ISSUE TITLE
Best practice visavi clearItemsForDomains

### ISSUE THREAD

**Issue by hessius** [MarcoEidinger/cordova-plugin-indexappcontent-sampleApp#1]
Saw that you call the clear items function and on success call the set items.
Is this best practice?
In my tests just setting items without clearing items first seems to work fine without causing duplicates - Is there a benefit to do this? (if conclusively yes, shouldn't clearing be baked into the set items function?)

**Comment by MarcoEidinger** [comment]
Thanks for your question. No, it's not a best practice.  The sample app just illustrates the use of the function.

I cannot tell you what's the result when using duplicate identifiers as the iOS documentation does not specify it. Best practice here: the consumer should either specify a unique identifier or should not provide at all. In the latter case the iOS will generate a unique identifier.
